repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        files: ^backend-flask/
        args:
          - --maxkb=1000
      - id: check-toml
        files: ^backend-flask/
      - id: check-yaml
        files: ^backend-flask/
        args:
          - --unsafe
      - id: check-json
        files: ^backend-flask/
      - id: end-of-file-fixer
        files: ^backend-flask/
      - id: trailing-whitespace
        files: ^backend-flask/

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        files: ^backend-flask/.*\.py$
        args:
          - --fix
      - id: ruff-format
        files: ^backend-flask/.*\.py$

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.363
    hooks:
      - id: pyright
        files: ^backend-flask/.*\.py$
        args:
          - --project
          - backend-flask/pyrightconfig.json

  - repo: local
    hooks:
      - id: requirements
        name: export requirements
        language: system
        files: ^backend-flask/pyproject.toml$
        pass_filenames: false
        entry: uv pip compile backend-flask/pyproject.toml -o backend-flask/requirements.txt
      - id: requirements-test
        name: export requirements-test
        language: system
        files: ^backend-flask/pyproject.toml$
        pass_filenames: false
        entry: uv pip compile backend-flask/pyproject.toml --all-extras -o backend-flask/requirements-test.txt

  - repo: https://github.com/djlint/djLint
    rev: v1.35.2
    hooks:
      - id: djlint-reformat-jinja
        name: djLint HTML Formatter
        files: "^backend-flask/ceylonroots/templates/.*\\.html$"
        types_or: ["html"]
